#pragma once

enum PacketType : uint32_t {
    HANDSHAKE = 0, LOGIN = 1, LOGIN_SUCCESS = 2, LOGIN_ERROR = 3, REGISTER = 4, REGISTER_SUCCES = 5, REGISTER_ERROR = 6,
    CREATE_ROOM = 7, CREATE_ROOM_SUCCES = 8, CREATE_ROOM_ERROR = 9, JOIN_ROOM = 10, JOIN_ROOM_SUCCES = 11, JOIN_ROOM_ERROR = 12,
    START_GAME = 13, START_GAME_SUCCES = 14, DISCONNECT = 15, END_TURN = 16, END_TURN_SUCCES = 17
};
