#pragma once

enum PacketType { 
	HANDSHAKE, LOGIN, LOGIN_SUCCESS, LOGIN_ERROR, 
	REGISTER, REGISTER_SUCCES, REGISTER_ERROR, 
	CREATE_ROOM, CREATE_ROOM_SUCCES, CREATE_ROOM_ERROR, 
	JOIN_ROOM, JOIN_ROOM_SUCCES, JOIN_ROOM_ERROR, 
	DISCONNECT, TEST, WAIT 
};
